language: android

env:
  global:
    # ORG_GRADLE_PROJECT_keystorePassword.
    - secure: "TGGsl0Jdc6cKt0dHarl6/YobzOZTxtxGCSZiwDPZn2Qe2IAUb8JssvTviOkCtbXQesdjcHuvpVlG70Yz0sISxTanwJI6yRMmqAOm6mfr1bVvcaeFIXXEm1s8q8rQfHxOv0BTMxLQ2MdYkz6MteTOcn722e0NEs+lh73aSbCi0Os="

    # ORG_GRADLE_PROJECT_keystoreKeyPassword.
    - secure: "KbIFt5KMY6sMLsMtYQDbHUX8MtYQSY+6Lj9qc+jJdTAukc2qAtJLNyXKKQlG5pyoSN/F/hVBJKbmDDz2AY6ifMZkOpzVVKlN8E2MPG1BCln0BwMJactL1kLb+287oFg6tXDc6YoxImeKlpFMucy2RjeWwtZptmbsUiXT2UwhPn8="

android:
  components:
    # Specify the components that are needed to build the project.
    # 'tools' is listed twice on purpose (to get the newest version).
    - tools
    - platform-tools
    - tools

    # Build tools & SDK.
    - build-tools-28.0.3
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

install:
  # Installs the NDK.
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.10.2.4988404"

before_script:
  # Decrypts the keystore (if this is not a PR build).
  - 'if [ ${TRAVIS_SECURE_ENV_VARS} = "true" ]; then
       openssl aes-256-cbc -d
         -K $encrypted_d213628fe2b0_key -iv $encrypted_d213628fe2b0_iv
         -in keystores/warmshowers.jks.enc -out "$HOME/warmshowers.jks" &&
       export ORG_GRADLE_PROJECT_keystoreFile="$HOME/warmshowers.jks";
     fi'

  # Sets the (public) keystore settings.
  - export ORG_GRADLE_PROJECT_keystoreKeyAlias="wsandroid"

  # Sets the NDK path.
  - export ANDROID_NDK_HOME="$ANDROID_HOME/ndk-bundle"

before_cache:
  # Cleans up the cache.
  - rm -f  "$HOME/.gradle/caches/modules-2/modules-2.lock"
  - rm -fR "$HOME/.gradle/caches/*/plugin-resolution/"
  - rm -f  "$HOME/warmshowers.jks"

cache:
  directories:
    - "$HOME/.android/build-cache"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_deploy:
  - mv app/build/outputs/apk/floss/release/app-floss-release.apk wsandroid-${TRAVIS_TAG}-floss.apk
  - mv app/build/outputs/apk/google/release/app-google-release.apk wsandroid-${TRAVIS_TAG}-google.apk

deploy:
  # Deploys the release APK for tagged revisions to GitHub.
  provider: releases
  api_key:
    secure: "dIzw4tJxXLPlA7wDdcgwLop6qcAU9lPTD4Z322APx6430Pevx93o6u8H6vnNMPytbpL4kpsxQjsqe+gz3DLB5vSUmftn0UF5GrjJTxNCeSj0wxW5kgeb2iuw4UsjpoI1FOroN0FxOg+CJUoD27MRwjjl4S9NnEVYmbcj9+8O8f4="
  file:
    - "wsandroid-${TRAVIS_TAG}-floss.apk"
    - "wsandroid-${TRAVIS_TAG}-google.apk"
  skip_cleanup: true
  on:
    tags: true
